/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.wargame.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
/**
 *
 * @author Mateo Unda
 */
public class FrmGameTimer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGameTimer.class.getName());
private javax.swing.Timer blinkTimer;
private Timer timer;
private TimerTask task;
private long remainingMillis;
private boolean isRunning = false;
private boolean isBlinking = false;
private void startBlinking() {
    isBlinking = true;
blinkTimer = new javax.swing.Timer(500, e -> {
        Color currentColor = lblViewTime.getForeground();
        lblViewTime.setForeground(currentColor.equals(Color.RED) ? Color.WHITE : Color.RED);
    });
    blinkTimer.start();
}
    /**
     * Creates new form FrmGameTimer
     */
    public FrmGameTimer() {
        initComponents();
                Font largeBoldFont = new Font("Segoe UI", Font.BOLD, 25);
        lblViewTime.setFont(largeBoldFont);

    Color darkGreen = new Color(85, 107, 47);

btnStart.setBackground(darkGreen);
btnStart.setForeground(Color.WHITE);

btnPause.setBackground(darkGreen);
btnPause.setForeground(Color.WHITE);

btnContinue.setBackground(darkGreen);
btnContinue.setForeground(Color.WHITE);

btnReboot.setBackground(darkGreen);
btnReboot.setForeground(Color.WHITE);

btnBack.setBackground(darkGreen);
btnBack.setForeground(Color.WHITE);
lblViewTime.setForeground(Color.RED);
    }
  private void startTimer(long durationMillis) {
    if (isRunning) {
        showMessage("El temporizador ya está en marcha.");
        return;
    }
        remainingMillis = durationMillis;

    task = new TimerTask() {
        @Override
        public void run() {
            if (remainingMillis <= 0) {
                timer.cancel();
                isRunning = false;
                lblViewTime.setText("¡El tiempo ha terminado!");
            } else {
                long minutes = (remainingMillis / 1000) / 60;
                long seconds = (remainingMillis / 1000) % 60;
                lblViewTime.setText(String.format("Tiempo restante: %02d:%02d", minutes, seconds));
                remainingMillis -= 1000;
            }
        }
    };

    timer = new Timer();
    timer.scheduleAtFixedRate(task, 0, 1000);
    isRunning = true;
}

private void pauseTimer() {
    if (!isRunning) {
        showMessage("El temporizador no está activo.");
        return;
    }
    timer.cancel();
    isRunning = false;
    showMessage("Temporizador pausado.");
}

private void resumeTimer() {
    if (isRunning) {
        showMessage("El temporizador ya está en marcha.");
        return;
    }
    startTimer(remainingMillis);
    showMessage("Temporizador reanudado.");
}

private void resetTimer() {
    if (timer != null) {
        timer.cancel();
    }
    isRunning = false;
    lblViewTime.setText(" ");
    txtDuration.setText("00:00");
    showMessage("Temporizador reiniciado.");
}

private long parseDuration() {
    String[] parts = txtDuration.getText().split(":");
    if (parts.length != 2) {
        showMessage("Formato de tiempo inválido. Usa MM:SS");
        return 0;
    }

    try {
        int minutes = Integer.parseInt(parts[0]);
        int seconds = Integer.parseInt(parts[1]);
        return (minutes * 60 + seconds) * 1000L;
    } catch (NumberFormatException e) {
        showMessage("Error al analizar el tiempo.");
        return 0;
    }
}

private void showMessage(String message) {
    javax.swing.JOptionPane.showMessageDialog(this, message);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JToggleButton();
        btnPause = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        btnReboot = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblViewTime = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Iniciar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnPause.setText("Pausar");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnContinue.setText("Continuar");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        btnReboot.setText("Reiniciar");
        btnReboot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRebootActionPerformed(evt);
            }
        });

        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblViewTime.setText(" ");

        lblLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Escritorio\\logoWarGame.jpg")); // NOI18N

        jLabel2.setText("Ingrese su tiempo:");

        txtDuration.setText("00:00");
        txtDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPause)
                            .addComponent(btnContinue)
                            .addComponent(btnStart)
                            .addComponent(btnReboot))
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(76, 76, 76)
                        .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblViewTime, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblViewTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPause)
                .addGap(18, 18, 18)
                .addComponent(btnContinue)
                .addGap(18, 18, 18)
                .addComponent(btnReboot)
                .addGap(15, 15, 15)
                .addComponent(btnBack)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        long durationMillis = parseDuration();
        if (durationMillis > 0) {
            startTimer(durationMillis);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        pauseTimer();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        resumeTimer();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnRebootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRebootActionPerformed
        resetTimer();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRebootActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGameTimer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnReboot;
    private javax.swing.JToggleButton btnStart;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblViewTime;
    private javax.swing.JTextField txtDuration;
    // End of variables declaration//GEN-END:variables
}
