/*
                        Univesidad de las Fuerzas Armadas ESPE
                                Ingeniería de Software
Nombres: Joseph Gallardo, Jonathan Guayta, Andrés Hinojosa      Periodo: 202451
Asignatura: Programación Orientada a Objetos                    NRC: 1967
Fecha: 10/02/2025
Tema: Proyecto Juridico "AxisLaw"
Construcción de un sistema para el control y administración de trámites judiciales
 */
package ec.edu.espe.view;

import ec.edu.espe.model.Mensaje;
import ec.edu.espe.model.MensajeDAO;
import ec.edu.espe.controller.ControladorTablaMensajes;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andy
 */
public class reporteTramites extends javax.swing.JFrame {

    /**
     * Creates new form reporteTramites
     */
    public reporteTramites() {
        initComponents();
        this.setLocationRelativeTo(null);
        tablaMensajes.setDefaultEditor(Object.class, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMensajes = new javax.swing.JTable();
        jButtonBuscar2 = new javax.swing.JButton();
        jTextFieldBuscar2 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);

        tablaMensajes.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 14)); // NOI18N
        tablaMensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID TRAMITE", "ID CLIENTE", "TIPO DE TRAMITE", "DESCRIPCION ", "DOCUMENTACION REQUERIDA", "STATUS", "COSTO ESTIMADO", "TIEMPO ESTIMADO", "COSTO REAL", "TIEMPO REAL", "FECHA INICIO", "FECHA FIN", "OBSERVACIONES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMensajes.setOpaque(false);
        tablaMensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMensajesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaMensajes);

        jButtonBuscar2.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 30)); // NOI18N
        jButtonBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search (1).png"))); // NOI18N
        jButtonBuscar2.setText("BUSCAR");
        jButtonBuscar2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonBuscar2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonBuscar2.setIconTextGap(15);
        jButtonBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscar2ActionPerformed(evt);
            }
        });

        jTextFieldBuscar2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextFieldBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscar2ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 30)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sandclock.png"))); // NOI18N
        jButton14.setText("ACTUALIZAR TABLA");
        jButton14.setPreferredSize(new java.awt.Dimension(350, 70));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dubai Medium", 1, 34)); // NOI18N
        jButton5.setText("X");
        jButton5.setAlignmentY(0.0F);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dubai Medium", 0, 80)); // NOI18N
        jButton3.setText("-");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(295, 295, 295))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar2)
                    .addComponent(jTextFieldBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1000X720.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMensajesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMensajesMouseClicked

    private void jButtonBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscar2ActionPerformed
        // Obtener el ID del mensaje para buscarlo
        String idMensajeStr = jTextFieldBuscar2.getText().trim();

        if (idMensajeStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un ID de mensaje para buscar.");
            return;
        }

// Convertir el ID a entero
        int idMensaje;
        try {
            idMensaje = Integer.parseInt(idMensajeStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID de mensaje debe ser un número válido.");
            return;
        }

        MensajeDAO mensajeDAO = new MensajeDAO();
        Mensaje mensaje = mensajeDAO.buscarPorIdMensaje(idMensaje);  // Buscar mensaje por ID

        DefaultTableModel model = (DefaultTableModel) tablaMensajes.getModel();
        model.setRowCount(0);  // Limpiamos la tabla antes de mostrar los resultados

        if (mensaje != null) {
            // Agregamos el mensaje encontrado a la tabla
            model.addRow(new Object[]{
                mensaje.getIdMensaje(),
                mensaje.getRemitente(),
                mensaje.getDestinatario(),
                mensaje.getAsunto(),
                mensaje.getCuerpo(),
                mensaje.getTipoMensaje(),
                mensaje.getObservacion(),
                mensaje.getFechaEnvio()
            });
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún mensaje con ese ID.");
        }

    }//GEN-LAST:event_jButtonBuscar2ActionPerformed

    private void jTextFieldBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscar2ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        // Actualizar los datos de la tabla de trámites
        ControladorTablaMensajes controlador = new ControladorTablaMensajes(tablaMensajes);  // tablaTramites es tu JTable
        controlador.cargarDatos();  // Recargar los datos en la tabla
        this.jTextFieldBuscar2.setText("");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed
// Método para obtener el ID del trámite seleccionado en la tabla

    private int obtenerIdMensajeSeleccionado() {
        int row = tablaMensajes.getSelectedRow();  // tablaMensajes es el JTable donde se listan los mensajes
        if (row != -1) {
            // Obtiene el ID de la primera columna (asegúrate de que la columna ID esté en la primera posición)
            return (int) tablaMensajes.getValueAt(row, 0);
        }
        return -1;  // Retorna -1 si no hay mensaje seleccionado
    }

    // Método para actualizar la lista de trámites en la interfaz
    private void actualizarListaMensajes() {
        // Recargar los mensajes desde la base de datos y actualizar la tabla
        MensajeDAO mDAO = new MensajeDAO();
        List<Mensaje> mensajes = mDAO.listar();  // Obtener la lista actualizada de mensajes

        // Actualizar la tabla con los nuevos datos
        DefaultTableModel model = (DefaultTableModel) tablaMensajes.getModel();
        model.setRowCount(0);  // Limpiar la tabla antes de agregar los nuevos mensajes

        // Llenar la tabla con los nuevos mensajes
        for (Mensaje m : mensajes) {
            model.addRow(new Object[]{
                m.getIdMensaje(), // Suponiendo que tienes un ID para los mensajes
                m.getRemitente(),
                m.getDestinatario(),
                m.getAsunto(),
                m.getTipoMensaje(),
                m.getFechaEnvio(),
                m.getObservacion()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reporteTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reporteTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reporteTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reporteTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporteTramites().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonBuscar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldBuscar2;
    public javax.swing.JTable tablaMensajes;
    // End of variables declaration//GEN-END:variables
}
