/*
                        Univesidad de las Fuerzas Armadas ESPE
                                Ingeniería de Software
Nombres: Joseph Gallardo, Jonathan Guayta, Andrés Hinojosa      Periodo: 202451
Asignatura: Programación Orientada a Objetos                    NRC: 1967
Fecha: 10/02/2025
Tema: Proyecto Juridico "AxisLaw"
Construcción de un sistema para el control y administración de trámites judiciales
 */
package ec.edu.espe.view;

import ec.edu.espe.model.Usuario;
import ec.edu.espe.model.UsuarioDAO;
import ec.edu.espe.controller.ControladorTablaUsuarios;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andy
 */
public class reporteUsuario extends javax.swing.JFrame {

    int id;

    /**
     * Creates new form reporteUsuario
     */
    public reporteUsuario() {
        initComponents();
        ocultarColumnas();
        this.setLocationRelativeTo(null);
        tablaUsuarios.setDefaultEditor(Object.class, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnBuscarUsuario = new javax.swing.JButton();
        jTextBuscarUsuario = new javax.swing.JTextField();
        btnActualizarTaUsuario = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        tablaUsuarios.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 14)); // NOI18N
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "USUARIO", "CONTRASEÑA", "ROL", "IDENTIFICACIÓN", "NACIMIENTO", "GENERO", "DIRECCIÓN", "TELÉFONO", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.setOpaque(false);
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        btnBuscarUsuario.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 30)); // NOI18N
        btnBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search (1).png"))); // NOI18N
        btnBuscarUsuario.setText("BUSCAR");
        btnBuscarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBuscarUsuario.setIconTextGap(15);
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        jTextBuscarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextBuscarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarUsuarioActionPerformed(evt);
            }
        });

        btnActualizarTaUsuario.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 30)); // NOI18N
        btnActualizarTaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sandclock.png"))); // NOI18N
        btnActualizarTaUsuario.setText("ACTUALIZAR TABLA");
        btnActualizarTaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarTaUsuario.setPreferredSize(new java.awt.Dimension(350, 70));
        btnActualizarTaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTaUsuarioActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dubai Medium", 1, 34)); // NOI18N
        jButton5.setText("X");
        jButton5.setAlignmentY(0.0F);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dubai Medium", 0, 80)); // NOI18N
        jButton3.setText("-");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarTaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(295, 295, 295))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizarTaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarUsuario)
                    .addComponent(jTextBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1000X720.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        int fila = tablaUsuarios.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Selecciona un usuario para modificar.");
        } else {
            // Obtener los valores de la fila seleccionada
            id = Integer.parseInt(tablaUsuarios.getValueAt(fila, 0).toString());
            String usuario = (String) tablaUsuarios.getValueAt(fila, 1);
            String password = (String) tablaUsuarios.getValueAt(fila, 2);
            String tipoUsuario = (String) tablaUsuarios.getValueAt(fila, 3);
            String nombreCompleto = (String) tablaUsuarios.getValueAt(fila, 4);
            String ciPasport = (String) tablaUsuarios.getValueAt(fila, 5);
            String fNacimiento = (String) tablaUsuarios.getValueAt(fila, 6);
            String genero = (String) tablaUsuarios.getValueAt(fila, 7);
            String direccion = (String) tablaUsuarios.getValueAt(fila, 8);
            String telefono = (String) tablaUsuarios.getValueAt(fila, 9);
            String email = (String) tablaUsuarios.getValueAt(fila, 10);

        }
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        String ciPasport = jTextBuscarUsuario.getText().trim();

        if (ciPasport.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un CI para buscar.");
            return;
        }

        UsuarioDAO uDAO = new UsuarioDAO();
        List<Usuario> usuarios = uDAO.buscarPorCiPasport(ciPasport); // Cambiado a lista

        DefaultTableModel model = (DefaultTableModel) tablaUsuarios.getModel();
        model.setRowCount(0);  // Limpiamos la tabla

        if (!usuarios.isEmpty()) {
            // Iteramos sobre la lista de usuarios encontrados y los agregamos a la tabla
            for (Usuario usuario : usuarios) {
                model.addRow(new Object[]{
                    usuario.getId(),
                    usuario.getUsuario(),
                    usuario.getPassword(),
                    usuario.getTipoUsuario(),
                    usuario.getNombreCompleto(),
                    usuario.getCiPasport(),
                    usuario.getfNacimiento(),
                    usuario.getGenero(),
                    usuario.getDireccion(),
                    usuario.getTelefono(),
                    usuario.getEmail()
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún usuario con ese CI.");
        }
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void jTextBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBuscarUsuarioActionPerformed

    private void btnActualizarTaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTaUsuarioActionPerformed
        // Actualizar los datos de la tabla
        ControladorTablaUsuarios controlador = new ControladorTablaUsuarios(tablaUsuarios);  // tablaUsuarios es tu JTable
        controlador.cargarDatos();  // Recargar los datos en la tabla
        ocultarColumnas();
        this.jTextBuscarUsuario.setText("");
    }//GEN-LAST:event_btnActualizarTaUsuarioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ocultarColumnas() {
        tablaUsuarios.getColumnModel().getColumn(2).setMinWidth(0);  // Usuario (índice 2)
        tablaUsuarios.getColumnModel().getColumn(2).setMaxWidth(0);
        tablaUsuarios.getColumnModel().getColumn(2).setPreferredWidth(0);

        tablaUsuarios.getColumnModel().getColumn(3).setMinWidth(0);  // Contraseña (índice 3)
        tablaUsuarios.getColumnModel().getColumn(3).setMaxWidth(0);
        tablaUsuarios.getColumnModel().getColumn(3).setPreferredWidth(0);
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

// Método para obtener el ID del usuario seleccionado en la tabla
    private int obtenerIdUsuarioSeleccionado() {
        int row = tablaUsuarios.getSelectedRow();  // jTableUsuarios es el JTable donde se listan los usuarios
        if (row != -1) {
            // Obtiene el ID de la primera columna (asegúrate de que la columna ID esté en la primera posición)
            return (int) tablaUsuarios.getValueAt(row, 0);
        }
        return -1;  // Retorna -1 si no hay usuario seleccionado
    }

    // Método para actualizar la lista de usuarios en la interfaz
    private void actualizarListaUsuarios() {
        //Recargar usuarios desde la base de datos y actualiza la tabla 
        UsuarioDAO uDAO = new UsuarioDAO();
        List<Usuario> usuarios = uDAO.listar();  // Obtener la lista actualizada de usuarios

        // Actualizar la tabla con los nuevos datos
        DefaultTableModel model = (DefaultTableModel) tablaUsuarios.getModel();
        model.setRowCount(0);  // Limpiar la tabla antes de agregar los nuevos usuarios

        // Llenar la tabla con los nuevos usuarios
        for (Usuario u : usuarios) {
            model.addRow(new Object[]{
                u.getId(),
                u.getUsuario(),
                u.getPassword(),
                u.getTipoUsuario(),
                u.getNombreCompleto(),
                u.getCiPasport(),
                u.getfNacimiento(),
                u.getGenero(),
                u.getDireccion(),
                u.getTelefono(),
                u.getEmail()
            });
        }
        ocultarColumnas();
    }
// Método para actualizar la lista de clientes en la interfaz

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reporteUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reporteUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reporteUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reporteUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporteUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTaUsuario;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextBuscarUsuario;
    public javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
