/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ec.edu.espe.wargame.view;

import ec.edu.espe.wargame.model.Director;
import ec.edu.espe.wargame.model.Event;
import ec.edu.espe.wargame.model.EventManager;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FrmEventManager extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEventManager.class.getName());

    /**
     * Creates new form FrmEventManager
     */
    public FrmEventManager() {
        initComponents();
txtTitle.setEnabled(false);
txtDescription.setEnabled(false);
txtCreator.setEnabled(false);
}
private final EventManager eventManager = new EventManager();
private boolean isCreating = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        lblCreator = new javax.swing.JLabel();
        txtCreator = new javax.swing.JTextField();
        btnCreate = new javax.swing.JToggleButton();
        btnRead = new javax.swing.JButton();
        lblRead = new javax.swing.JLabel();
        lblEventList = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Título");

        lblDescription.setText("Descripción: ");

        txtTitle.setText("Inserte el título");

        txtDescription.setText("Inserte una descripción");
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        lblCreator.setText("Usuario creador: ");

        txtCreator.setText("Inserte el creador");

        btnCreate.setText("Crear evento");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRead.setText("Ver eventos");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        lblRead.setText("Eventos Cargados");

        lblEventList.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDescription)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDescription))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTitle)
                                    .addGap(52, 52, 52)
                                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCreator)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCreate)
                                        .addGap(71, 71, 71)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRead)
                                            .addComponent(btnRead)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblEventList, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreator)
                    .addComponent(txtCreator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnRead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEventList, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
if (!isCreating) {
    // Desbloquea los campos
    txtTitle.setEnabled(true);
    txtDescription.setEnabled(true);
    txtCreator.setEnabled(true);
    isCreating = true;
    btnCreate.setText("Guardar evento");
} else {
    // Guarda el evento
    String title = txtTitle.getText();
    String description = txtDescription.getText();
    String creator = txtCreator.getText();

    if (title.isEmpty() || description.isEmpty() || creator.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor llena todos los campos.");
        return;
    }

    Director director = new Director(creator, "");
    eventManager.createEvent(director, title, description);

    // Limpia y bloquea
    txtTitle.setText("");
    txtDescription.setText("");
    txtCreator.setText("");
    txtTitle.setEnabled(false);
    txtDescription.setEnabled(false);
    txtCreator.setEnabled(false);
    isCreating = false;
    btnCreate.setText("Crear evento");

    JOptionPane.showMessageDialog(this, "Evento creado exitosamente.");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
List<Event> events = eventManager.getEvents();

    if (events.isEmpty()) {
        lblEventList.setText("No hay eventos disponibles.");
    } else {
        StringBuilder sb = new StringBuilder("<html>");
        for (Event e : events) {
            sb.append("<b>Título:</b> ").append(e.getTitle()).append("<br>");
            sb.append("<b>Descripción:</b> ").append(e.getDescription()).append("<br>");
            sb.append("<b>Creado por:</b> ").append(e.getCreator().getUsername()).append("<br><br>");
        }
        sb.append("</html>");
        lblEventList.setText(sb.toString());
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            new FrmEventManager().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCreate;
    private javax.swing.JButton btnRead;
    private javax.swing.JLabel lblCreator;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblEventList;
    private javax.swing.JLabel lblRead;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCreator;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

